stages:
  - test

test-job:
  stage: test
  script:
    - echo "Running small tests"
    - python3 driver.py test-data/small.txt python3 sut.py
    - echo "Lookup tests"
    - python3 driver.py test-data/lookup.txt python3 sut.py
    - python3 driver.py test-data/lookup_big.txt python3 sut.py
    - echo "Remove tests"
    - python3 driver.py test-data/remove.txt python3 sut.py
    - python3 driver.py test-data/remove_big.txt python3 sut.py
    - echo "Lowerbound tests"
    - python3 driver.py test-data/lowerbound.txt python3 sut.py
    - python3 driver.py test-data/lowerbound_big.txt python3 sut.py

